### Upload Attach
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTUwODEwOSwiZXhwIjoxNzY5NTk0NTA5fQ.V2NKbnzPA0dWDThre9_vSMWpcHyvgROEaz2CUNyTiBh41Qgwg3BAxg4Eww_OECRuCWyGvcHGpoL1jRpWQNXvyQ

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Developer.jpg"

< E:\PHOTOS\Developer.jpg

### Open Attach
PUT http://localhost:8080/attach/open/0b46f728-1a13-4c73-be83-8d2ee3dede0c.jpg