### Registration
POST localhost:8080/api/v1/auth/registration
Content-Type: application/json
Accept-Language: UZ

{
  "name": "Muhammadjonov Muhammad Bobur",
  "username": "sardorbek.uktamov.1@mail.ru",
  "password": "12345",
  "gender": "MALE",
  "birthDate": "1998-09-25",
  "termsAccepted": true
}

### Registration verification
GET http://localhost:8080/api/v1/auth/registration/verification/1

### Registration sms verification
POST localhost:8080/api/v1/auth/registration/sms-verification
Content-Type: application/json
Accept-Language: UZ

{
  "phoneNumber": "998972710631",
  "code": "58246"
}

### Registration sms verification RESENT
POST localhost:8080/auth/registration/sms-verification-resent
Content-Type: application/json
Accept-Language: UZ

{
  "phoneNumber": "998911576777"
}

### RESET PASSWORD
POST localhost:8080/auth/registration/reset-password
Content-Type: application/json
Accept-Language: UZ

{
  "username": "uktamov9198@mail.ru"
}

### RESET PASSWORD CONFIRM
POST localhost:8080/auth/registration/reset-password-confirm
Content-Type: application/json
Accept-Language: UZ

{
  "username": "uktamov9198@mail.ru",
  "confirmCode": "68775",
  "password": "12345"
}

### Login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "username": "sardorbek.uktamov.1@mail.ru",
  "password": "12345"
}

### admin-tokeni eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTQxNDUxMSwiZXhwIjoxNzY5NTAwOTExfQ.QfTS0TWrcytTNpGHnziF__Wa-1lUqfPjmHFuRS-t4goZa1kXQ-1eodd2AQ_0dtj-_CjcCD2Y1JukzMcXNDK4qQ