### O'zgaruvchilar (O'zingizning Tokenlaringizni qo'ying)
@userToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzYXJkb3JiZWsudWt0YW1vdi4xQG1haWwucnUiLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMTYiLCJpYXQiOjE3Njk3NjY1MTEsImV4cCI6MTc2OTg1MjkxMX0.et-h0nzKeeJ9WEXuQvbUqXQ26iZnLlQehF8m_oBV2euDlIi_8WVWvQmm-YuCfEySg8wqXDrgO4Dge7H4TKcTqw
@adminToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTY5OTI0NywiZXhwIjoxNzY5Nzg1NjQ3fQ.Zv8hFh6OMj714P8WBNTQi5S5heVbt9hKqtVTwPFpdoxg1-k4_nYPl5InOjSJxdu4foFcKKHRjogha7uHoumJXw

###
# ---------------------------------------------------------
# 1-QADAM: DIPLOM YUKLASH (Attach Moduli orqali)
# Qaytib kelgan "id" ni nusxalab oling va pastdagi "diplomaId" ga qo'ying.
# ---------------------------------------------------------
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzYXJkb3JiZWsudWt0YW1vdi4xQG1haWwucnUiLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMTYiLCJpYXQiOjE3Njk3NjY1MTEsImV4cCI6MTc2OTg1MjkxMX0.et-h0nzKeeJ9WEXuQvbUqXQ26iZnLlQehF8m_oBV2euDlIi_8WVWvQmm-YuCfEySg8wqXDrgO4Dge7H4TKcTqw

--boundary
Content-Disposition: form-data; name="file"; filename="DXM.jpg"
Content-Type: image/jpeg

< E:\HUJJATLAR\\DXM.jpg
--boundary--

###

# ---------------------------------------------------------
# 2-QADAM: ARIZA TOPSHIRISH (User)
# "diplomaId" ga yuqoridagi response dagi ID ni qo'ying.
# Degree turlari: STUDENT, BACHELOR, MASTER, PHD, RESIDENCY
# ---------------------------------------------------------
POST http://localhost:8080/api/v1/doctor-apply
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzYXJkb3JiZWsudWt0YW1vdi4xQG1haWwucnUiLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMTYiLCJpYXQiOjE3NzEwODM2MTAsImV4cCI6MTc3MTE3MDAxMH0.0HGGe-P-LLc7ghY28N6iLct75lw77rZoX9dXvg-rTCHTWlvOZUAY2NfP9rUqxNu-vkAqLLQWFXsaNkIMVG7rLg

{
  "speciality": "Kardiolog",
  "universityName": "Toshkent Tibbiyot Akademiyasi",
  "degree": "BACHELOR",
  "graduatedDate": "2018-06-25",
  "experienceYear": 5,
  "currentWorkplace": "Akfa Medline",
  "diplomPhotoIds": [
    "1ac6ecd5-3300-40b1-883f-0af47e1e88f0.jpg",
    "d9c2ca8d-c07a-4b7c-b404-4019b493e8f0.jpg"
  ],

  "certificatePhotoIds": [
    "c3c14865-749d-42f9-b1d2-93f9d44368d1.jpg",
    "14f68b64-be2c-4010-881c-9b420bb3e260.jpg"
  ],
  "agreementPolicy": true
}

###

# ---------------------------------------------------------
# 3-QADAM: ARIZANI TASDIQLASH (Admin)
# User -> Doctor roliga o'tadi.
# URL dagi "1" bu doctor_details jadvalidagi ID (ariza ID si).
# ---------------------------------------------------------
PUT http://localhost:8080/api/v1/doctor-apply/change-status/1?status=APPROVED
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJpZCI6IjEiLCJpYXQiOjE3NzEwNjk1MzAsImV4cCI6MTc3MTE1NTkzMH0.MVeXDpYm9xpJulGSveomotA2Rz5hDb2xh607mK8Otso0G4WrU_LN5jr_yh0OzKY2nw8dtrKnIFDEpup0pPppVQ

###

# ---------------------------------------------------------
# 3.1-QADAM: ARIZANI RAD ETISH (Admin)
# Rad etishda "reason" yozish majburiy.
# ---------------------------------------------------------
PUT http://localhost:8080/api/v1/doctor-apply/change-status/1?status=REJECTED&reason=Diplom+xira+tushgan+qayta+yuklang
Content-Type: application/json
Authorization: Bearer {{adminToken}}

###

# ---------------------------------------------------------
# 4-QADAM: ADMIN KO'RISHI (Full Data)
# Bunda Diplom URL va Rad etish sabablari ko'rinadi.
# URL dagi "1" bu doctor_details jadvalidagi ID (ariza ID si).
# ---------------------------------------------------------
GET http://localhost:8080/api/v1/doctor-apply/admin/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTY5OTI0NywiZXhwIjoxNzY5Nzg1NjQ3fQ.Zv8hFh6OMj714P8WBNTQi5S5heVbt9hKqtVTwPFpdoxg1-k4_nYPl5InOjSJxdu4foFcKKHRjogha7uHoumJXw

###

# ---------------------------------------------------------
# 5-QADAM: PUBLIC KO'RISH (Bemorlar uchun)
# Bunda faqat tasdiqlangan (APPROVED) doktor ko'rinadi.
# Diplom va sabablar ko'rinmaydi.
# ---------------------------------------------------------
GET http://localhost:8080/api/v1/doctor-apply/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzYXJkb3JiZWsudWt0YW1vdi4xQG1haWwucnUiLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMTYiLCJpYXQiOjE3Njk3NjY1MTEsImV4cCI6MTc2OTg1MjkxMX0.et-h0nzKeeJ9WEXuQvbUqXQ26iZnLlQehF8m_oBV2euDlIi_8WVWvQmm-YuCfEySg8wqXDrgO4Dge7H4TKcTqw

### Login SUER-ADMIN
POST localhost:8080/api/v1/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "username": "998911576777",
  "password": "12345"
}

### Login DOCTOR
POST localhost:8080/api/v1/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "username": "sardorbek.uktamov.1@mail.ru",
  "password": "12345"
}