### 1. Kasallik tarixini qo'shish (To'liq)-Qizimni ID si
POST http://localhost:8080/api/v1/health-record/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTUwODEwOSwiZXhwIjoxNzY5NTk0NTA5fQ.V2NKbnzPA0dWDThre9_vSMWpcHyvgROEaz2CUNyTiBh41Qgwg3BAxg4Eww_OECRuCWyGvcHGpoL1jRpWQNXvyQ

{
  "patientId": "5dc7b66b-1126-430c-89fa-8c0b5dbcf68a",
  "diseaseName": "test",
  "recordDate": "2026-01-26",
  "doctorName": "test",
  "hospitalName": null,
  "treatment": "test",
  "note": "test",
  "isCritical": false,
  "photoId": "39d27dd9-026e-4325-8213-4912e8f55d17.png"
}

### 2. Tarixni ko'rish (Ro'yxat)
GET http://localhost:8080/api/v1/health-record/list/5dc7b66b-1126-430c-89fa-8c0b5dbcf68a
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTUwODEwOSwiZXhwIjoxNzY5NTk0NTA5fQ.V2NKbnzPA0dWDThre9_vSMWpcHyvgROEaz2CUNyTiBh41Qgwg3BAxg4Eww_OECRuCWyGvcHGpoL1jRpWQNXvyQ

### 2. ID orqali kasallik tarixni ko'rish
GET http://localhost:8080/api/v1/health-record/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTUwODEwOSwiZXhwIjoxNzY5NTk0NTA5fQ.V2NKbnzPA0dWDThre9_vSMWpcHyvgROEaz2CUNyTiBh41Qgwg3BAxg4Eww_OECRuCWyGvcHGpoL1jRpWQNXvyQ


### 3. Tahrirlash (Update)
PUT http://localhost:8080/api/v1/health-record/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTUwODEwOSwiZXhwIjoxNzY5NTk0NTA5fQ.V2NKbnzPA0dWDThre9_vSMWpcHyvgROEaz2CUNyTiBh41Qgwg3BAxg4Eww_OECRuCWyGvcHGpoL1jRpWQNXvyQ

{
  "diseaseName": "Kuchli grip ,O'tkir shamollash bo'lishi",
  "recordDate": "2025-09-01",
  "doctorName": "DR.Numonjonaka",
  "hospitalName": "Hospital City",
  "treatment": "L-montus 1/2 ikki maxal",
  "note": "Yo'tal, istima",
  "photoId": "39d27dd9-026e-4325-8213-4912e8f55d17.png",
  "isCritical": false
}

### 4. O'chirish (Delete)
DELETE http://localhost:8080/api/v1/health-record/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTQyMDUyMCwiZXhwIjoxNzY5NTA2OTIwfQ.Rk6TKPMnKItxB_EZYu1XBs03KZfKVbJlgPpXfGziq8ByC_y0ShELtXMNGasOLfnUrV2HB3DgTCkUlw_Rk3G_pQ

### Global Search
POST http://localhost:8080/api/v1/health-record/search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTUwODEwOSwiZXhwIjoxNzY5NTk0NTA5fQ.V2NKbnzPA0dWDThre9_vSMWpcHyvgROEaz2CUNyTiBh41Qgwg3BAxg4Eww_OECRuCWyGvcHGpoL1jRpWQNXvyQ

{
  "text": "buzili",
  "fromDate": "2025-01-01"
}


### Login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "username": "998911576777",
  "password": "12345"
}