### Upload Attach
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJpZCI6IjEiLCJpYXQiOjE3Njk2MTg2OTEsImV4cCI6MTc2OTcwNTA5MX0.Y3dbTEJnFy-5AQ8erYa-Lt9o1VKR8tOBHfagw7xVsnOzJexU3aMNb02QHZqaCExucc27ENh_jbupKjIW9xdv1A

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="ican.jpg"

< E:\PHOTOS\ican.jpg


### 1. Kasallik tarixini qo'shish (To'liq)-Qizimni ID si
POST http://localhost:8080/api/v1/health-record/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJpZCI6IjEiLCJpYXQiOjE3Njk2MTg2OTEsImV4cCI6MTc2OTcwNTA5MX0.Y3dbTEJnFy-5AQ8erYa-Lt9o1VKR8tOBHfagw7xVsnOzJexU3aMNb02QHZqaCExucc27ENh_jbupKjIW9xdv1A

{
  "patientId": "5dc7b66b-1126-430c-89fa-8c0b5dbcf68a",
  "diseaseName": "Ich buzilish",
  "recordDate": "2025-11-20",
  "doctorName": "DR.Numonaka",
  "hospitalName": "Do'mdagi uyida davoladi",
  "treatment": "Erseflora 3 maxal, Klizma qilish 2 maxal",
  "note": "Istima chiqdi, ko'ngil ayish bo'ldi",
  "isCritical": false,
  "photoIds": [
    "1c77e7dc-b9ec-4cb4-96ca-fb7d2a3a92e0.png",
    "3840ccda-bc6b-4a01-80ae-92485653da24.png",
    "0b4ab2a2-5cdc-4b25-975c-1c34878f7558.png"
  ]
}

### 2. Tarixni ko'rish (Ro'yxat)
GET http://localhost:8080/api/v1/health-record/list/5dc7b66b-1126-430c-89fa-8c0b5dbcf68a
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJpZCI6IjEiLCJpYXQiOjE3Njk2MTg2OTEsImV4cCI6MTc2OTcwNTA5MX0.Y3dbTEJnFy-5AQ8erYa-Lt9o1VKR8tOBHfagw7xVsnOzJexU3aMNb02QHZqaCExucc27ENh_jbupKjIW9xdv1A

### 2. ID orqali kasallik tarixni ko'rish
GET http://localhost:8080/api/v1/health-record/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJpZCI6IjEiLCJpYXQiOjE3Njk2MTg2OTEsImV4cCI6MTc2OTcwNTA5MX0.Y3dbTEJnFy-5AQ8erYa-Lt9o1VKR8tOBHfagw7xVsnOzJexU3aMNb02QHZqaCExucc27ENh_jbupKjIW9xdv1A


### 3. Tahrirlash (Update)
PUT http://localhost:8080/api/v1/health-record/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJpZCI6IjEiLCJpYXQiOjE3Njk2MTg2OTEsImV4cCI6MTc2OTcwNTA5MX0.Y3dbTEJnFy-5AQ8erYa-Lt9o1VKR8tOBHfagw7xVsnOzJexU3aMNb02QHZqaCExucc27ENh_jbupKjIW9xdv1A

{
  "diseaseName": "Ich buzilish",
  "recordDate": "2025-09-01",
  "doctorName": "DR.Numonjonaka",
  "hospitalName": "Hospital City",
  "treatment": "L-montus 1/2 ikki maxal",
  "note": "Yo'tal, istima",
  "photoIds": [
    "f5c76251-6626-4bf5-845f-d73b29945d9d.png"
  ],
  "isCritical": false
}

### 4. O'chirish (Delete)
DELETE http://localhost:8080/api/v1/health-record/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTQyMDUyMCwiZXhwIjoxNzY5NTA2OTIwfQ.Rk6TKPMnKItxB_EZYu1XBs03KZfKVbJlgPpXfGziq8ByC_y0ShELtXMNGasOLfnUrV2HB3DgTCkUlw_Rk3G_pQ

### Global Search
POST http://localhost:8080/api/v1/health-record/search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTUwODEwOSwiZXhwIjoxNzY5NTk0NTA5fQ.V2NKbnzPA0dWDThre9_vSMWpcHyvgROEaz2CUNyTiBh41Qgwg3BAxg4Eww_OECRuCWyGvcHGpoL1jRpWQNXvyQ

{
  "text": "buzili",
  "fromDate": "2025-01-01"
}


### Login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "username": "998911576777",
  "password": "12345"
}