### Upload Attach
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUixST0xFX1NVUEVSQURNSU4sUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc3MjU2MDA1NiwiZXhwIjoxNzcyNjQ2NDU2fQ.1gZIDOebg8Yax_UJfl_YVb6cenRD8MKWaGXtSdA9u_UYwiSfnHfQwLf-hOUaiu7-1ZpLuahGf3D08bZw8FPx8Q

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="444.png"

< E:\PHOTOS\444.png

### Post create
POST localhost:8080/api/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzYXJkb3JiZWsudWt0YW1vdi4xQG1haWwucnUiLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiNDQiLCJpYXQiOjE3NzI1NjAxOTAsImV4cCI6MTc3MjY0NjU5MH0.wUuWvjNUAozF88n8onmrumw4zh1jICMIzdhRQLelbaokEDXKxFjC_vsJk-FOZdSFCRW6gBOdq_zRUokSrjPqag

{
  "title": "Yangi tibbiy post (Multi-media)",
  "content": "Ushbu postda bir nechta rasm va videolar mavjud.",
  "attachIdList": [
    "3e4b3708-98a6-45be-b125-ce6e4685ed58.png",
    "0454b804-9474-4ff5-a94d-de8995ca3cbe.png"
  ]
}

### Post UPDATE
PUT localhost:8080/api/v1/posts/ad8f2139-e322-444c-8b08-a86ba52e1156
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTE1NzY3NzciLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsImlhdCI6MTc2OTUwODEwOSwiZXhwIjoxNzY5NTk0NTA5fQ.V2NKbnzPA0dWDThre9_vSMWpcHyvgROEaz2CUNyTiBh41Qgwg3BAxg4Eww_OECRuCWyGvcHGpoL1jRpWQNXvyQ

{
  "title": "Tahrirlangan post (Multi-media)",
  "content": "Post mazmuni va rasmlari yangilandi.",
  "attachIdList": [
    "new-photo-1.png",
    "updated-video.mp4",
    "old-photo-kept.jpg"
  ]
}

### get Posts in Admin Profile filter by name, title
POST http://localhost:8080/api/v1/posts/admin-post-list/filter
Content-Type: application/json
Accept-Language: EN
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1a3RhbW92OTE5OEBtYWlsLnJ1Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTixST0xFX1NVUEVSQURNSU4iLCJpZCI6IjEiLCJpYXQiOjE3Njg5ODQ5ODAsImV4cCI6MTc2OTA3MTM4MH0.PLbQnZoNaG0o-gCF5q4HPw9zyY7qC-SEFydi4BAbO6YYEgLSbg7Fjtk_RHaK1p1mpToDYoSobcObFoq3H3b6ow

{
  "postQuery": null,
  "profileQuery": "6777"
}

### Profile Post List
GET localhost:8080/posts/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MDU4NDY4NjYiLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMTIyIiwiaWF0IjoxNzY1NzI4NTEwLCJleHAiOjE3NjU4MTQ5MTB9.UL4sVWqcbArXJkwdcxpsUHpVtn6oMHoc9oIye7IyHc8ObOldtNmaEXyv6cmDKVl6iTFoHRS5mopDW5ZMc1uiEw

### Profile Post by ID
GET localhost:8080/api/v1/posts/public/79b3217b-cb8a-4daf-9536-a85524b820f9
Content-Type: application/json


### Filter Post
POST localhost:8080/api/v1/posts/public/filter?page=1&size=3
Content-Type: application/json

{
  "query": null,
  "exceptId": null
}

### Get simipar Post List
POST localhost:8080/api/v1/posts/public/similar
Content-Type: application/json

{
  "exceptId": "79b3217b-cb8a-4daf-9536-a85524b820f9"
}

### Login -ADMIN
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "uktamov9198@mail.ru",
  "password": "12345"
}

### Login -USER
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "998911576777",
  "password": "12345"
}