### receive token for SMS
POST https://notify.eskiz.uz/api/auth/login
Content-Type: application/json

{
  "email": "uktamov9198@mail.ru",
  "password": "7RhtQCb7tlk3TqNdTxRevy7P9MCkphu3w7NdhZWx"
}

### get yser
GET https://notify.eskiz.uz/api/auth/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzIzNTE1MTAsImlhdCI6MTc2OTc1OTUxMCwicm9sZSI6InRlc3QiLCJzaWduIjoiMzgyMWQzMmUyZTE2OWEzZTRhMzRiNjFlNzk5MDc1ZjZjNDM0ZTk5NDA4NWE1YjUzZjkzZjcwZWQyOGEwZTIzYSIsInN1YiI6IjE0Mjg4In0.fh0MxmiwxZ5GZswqjdJzD1k_Z2gGQXdh6pKuWsQ6wfI

### send SMS
### receive token for SMS
POST https://notify.eskiz.uz/api/message/sms/send
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzIzNTE1MTAsImlhdCI6MTc2OTc1OTUxMCwicm9sZSI6InRlc3QiLCJzaWduIjoiMzgyMWQzMmUyZTE2OWEzZTRhMzRiNjFlNzk5MDc1ZjZjNDM0ZTk5NDA4NWE1YjUzZjkzZjcwZWQyOGEwZTIzYSIsInN1YiI6IjE0Mjg4In0.fh0MxmiwxZ5GZswqjdJzD1k_Z2gGQXdh6pKuWsQ6wfI

{
  "mobile_phone": "998911576777",
  "message": "Bu Eskiz dan test",
  "from": "4546"
}